### ISSUE TITLE
Is this important to fix? 

### ISSUE THREAD

**Issue by bayeslearner** [ozchamo/YAKKO#11]
STAGE 9: Configure Load Balancer  (Time start: 18:24PM)

The system's /etc/haproxy/haproxy.cfg seems to contain a mode directive for http
This will prevent HAproxy working for YAKKO.
Do you want to continue with this configuration for HAproxy (Y/N) [Y]?

**Comment by ozchamo** [comment]
Good point - I think I put that in because there was a time when installing haproxy would drop a demo haproxy.cfg file which used port 80, so I have deleted that check for the next release, which is in the making. Let's call that YAKKO 5.1 ;)
