### ISSUE TITLE
Any way to use YAKKO with a bridge0 device as my network?

### ISSUE THREAD

**Issue by jfrancin** [ozchamo/YAKKO#14]
Back in the dim mists of time I had to set up a bridge0 device on my test system where I'm trying to install YAKKO - it was to allow the VMs on this system to be externally reachable on the rest of my home network according to [the RHEL documentation here.](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/configuring-virtual-machine-network-connections_configuring-and-managing-virtualization#configuring-externally-visible-virtual-machines-using-the-command-line-interface_recommended-virtual-machine-networking-configurations-using-the-command-line-interface)

Yakko does not like this. Is there a way to allow it to work in this configuration, or must I reconfigure the system to use a physical interface and potentially lose direct access to my non-RHOCP VMs on my lab net?

**Comment by ozchamo** [comment]
Exposing a YAKKO cluster outside of its virtual network is probably doable and remains in the well of 'nice features that may be useful or nice". Then again, most OpenShift clusters live in a network that is not *yours" to live in :)
