### ISSUE TITLE
Error attaching ISO image to VM due to non-existent volume

### ISSUE THREAD

**Issue by fiiray** [ozchamo/YAKKO#15]
Hello, 

First and foremost massive thanks for the development and maintenance of this project. 

Are you able to help please @ozchamo 

```
Domain 'master-0.fii.fii.ninja.995' defined from /var/lib/libvirt/images/YAKKO-fii-fii.ninja-995/master-0.fii.fii.ninja.995.xml

ERROR    Error: --disk /home/fii/yokko/images/4.15.6/agent.x86_64.iso,device=cdrom,target.dev=sdc: Size must be specified for non existent volume 'agent.x86_64.iso'

ERROR: Could not attach ISO image to host master-0.fii.fii.ninja.995

ERROR: Could not build VM for node [master-0] - exiting...
Rollback steps of this stage (Y) or leave for debugging (N) (Y/N) [Y]?
ROLLBACK STAGE: Deleting OCP master nodes

Domain 'master-0.fii.fii.ninja.995' has been undefined
Volume 'vda'(/var/lib/libvirt/images/YAKKO-fii-fii.ninja-995/master-0.fii.fii.ninja.995.qcow2) removed.
````
Thanks 
fii

**Comment by ozchamo** [comment]
Hi @fiiray,

And thanks to you for giving YAKKO a try!

To be precise, if you are using YAKKO 7.1 that would be a symptom of line 1729:
virt-xml ${NODEVMNAME} --add-device --disk=${IMAGEREPO}/${OCPINSTALLVERSION}/agent.x86_64.iso,device=cdrom,target.dev=sdc --quiet

I don't understand why this doesn't work as is in your environment and I would love to confirm with you what O/S and version you are using (cat /etc/system-release), as well as virt-xml version (virt-xml --version). So please do post that here if you have a chance.

However, a quick wild workaround would be to add ",size=6" to the line above as part of the --disk parameters as follows:
virt-xml ${NODEVMNAME} --add-device --disk=${IMAGEREPO}/${OCPINSTALLVERSION}/agent.x86_64.iso,device=cdrom,target.dev=sdc,size=6 --quiet

This way, you should be addressing the exact issue of specifying a disk size, as pretty much all DVDs are about 6GB (and in reality the CDROM size will be smaller.)

**Comment by fiiray** [comment]
Thank you for the swift response. I'll attempt that and provide an update shortly. As requested. 
`cat /etc/system-release
Fedora release 39 (Thirty Nine)`

Cheers.

**Comment by ozchamo** [comment]
Hi @fiiray,

I tested a Single Node Npenshift (SNO) on my rig, which matches your versions - with and without the ",size=6" and both worked. Was your test with a SNO?
