### ISSUE TITLE
Possibility for attaching disks to the OCP cluster

### ISSUE THREAD

**Issue by leelavg** [ozchamo/YAKKO#16]
hello, I successfully created my first cluster w/ 8.02, thanks!

Before editing the script (if at all possible) may I know is there any way to attach empty disks to the VMs? As VM creation is done by yakko I don't think updating install-config w/ disks have any usefulness. I'm thinking of attaching a single disk (in addition to default root disk) to the VMs and have [lvms](https://github.com/openshift/lvm-operator) consume it.

Second, is it possible to share nfs created by yakko for different clusters image-registry and save on roundtrip/bandwidth of OCP images?

**Comment by ozchamo** [comment]
Hi lee? :)

While I have been giving this some thought as an extension to what YAKKO builds, you can REALLY easily add a disk using cockpit (https://www.redhat.com/sysadmin/intro-cockpit). 

I quickly added a 13GB disk to one of my SNOs (for luck) using cockpit, like so:
![image](https://github.com/user-attachments/assets/6ffbd525-b183-45ec-b7b4-7eb2bb8603cd)

Then did a magical "yakko infra sshtonode" to the master and found it there ready for further consumption:
![image](https://github.com/user-attachments/assets/2546e0e3-bf06-43f1-b585-36ab5dafa864)

Of course, in a multinode cluster you won't be able to share that device. But then maybe you don't need to if it's the storage to your registry... So as for sharing a registry, I really don't know if that's possible. I think that image registries keep a database and having others throw content is probably not a good idea. Try it and let me know ;)

**Comment by leelavg** [comment]
> Hi lee? :)
- Same Leela from https://github.com/ozchamo/YAKKO/issues/13#issuecomment-1953818982 😄

> I quickly added a 13GB disk to one of my SNOs (for luck) using cockpit, like so:
- ack, thanks a lot for checking it, I'll do as well but from virsh, I want to enable cockpit only if no other approach exist as it is power hungry (but provided insights are good though) when I tried it a couple of times.

> I think that image registries keep a database and having others throw content is probably not a good idea.
- I generally use k3d w/ this https://github.com/ligfx/k3d-registry-dockerd project which caches every image to local docker from any cluster and serves from there, reusing that w/ OCP is definitely pushing it to the limits, however trying something similar doesn't hurt 🤞🏼

> Try it and let me know ;)
- I have two machines but in their own they can't run more than one OCP so trying it and reporting could take time

Nevertheless, thanks again, got the answer, issue can be closed.
