### ISSUE TITLE
[Doc] DNS entries require a DNS server which accepts wildcard entries or several additional CNAME entries

### ISSUE THREAD

**Issue by aenertia** [ozchamo/YAKKO#3]
The Hint/Doc text suggests adding 'app'.<domain> entry pointing at the underlay network node IP/DNS when adding 'external access' 

Actually this requires half a dozen sub-subdomains; or adding wildcard to a full-blown DNS server (dnsmasq does not accept wildcard sub-subdomain entries, so bind/unbound etc) OR if adding to /etc/hosts you need each individual entry for things like console.<> and others.

Doc hints should explain and expand on what specific sub-sub domain entries are required in this case and explain the wildcard DNS issue.

**Comment by ozchamo** [comment]
Indeed this was WIP when YAKKO was first posted.  'yakko ops openaccess' now extends a larger helping hand to guide you through some immediate options - and it now offers adding dnsmasq entries in the YAKKO server to act as a DNS host to your network, as long as your clients can point to it. Ideally though, anyone running OpenShift will also have his/her own DNS and if it's dnsmasq, YAKKO will give you some guidelines. I use dnsmasq/pihole on a Raspberry Pi for many useful reasons, and yes, dnsmasq does accept wildcard subdomains, I'm not sure why you comment it cannot. Of course, the dnsmasq entry will point to the YAKKO server and it then hits the HAProxy loadbalancer running there, thus spreading the calls across the "cluster".

Importantly, setting up DNS for your wider network is really a prerequisite that goes beyond what YAKKO tries to achieve, but the above should help. For some documentation around the DNS prerequisities, visit this if possible: [https://docs.openshift.com/container-platform/4.6/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-dns-user-infra_installing-bare-metal-network-customizations](url)
