### ISSUE TITLE
OC command missing

### ISSUE THREAD

**Issue by GoKEV** [ozchamo/YAKKO#4]
It would be nice to include `oc` in this, but I wasn't sure where to tuck this into the script in a PR, so I'm tossing my suggestion here to somewhere add:

subscription-manager repos --enable="rhocp-4.3-for-rhel-8-x86_64-rpms"
dnf install openshift-clients

From the docs:
https://docs.openshift.com/container-platform/4.3/cli_reference/openshift_cli/getting-started-cli.html

**Comment by ozchamo** [comment]
Hi GoKEV - can you tell me what it is that you are trying to achieve - from an end-user perspective? Happy to entertain!
