### ISSUE TITLE
made my cockpit service unusable

### ISSUE THREAD

**Issue by bayeslearner** [ozchamo/YAKKO#9]
After running this a couple of times without success, 
I also noticed that cockpit at port 9090 is not working any more.  Probably due to conflict web service?

**Comment by ozchamo** [comment]
YAKKO will attempt running its web server on port 8080 or else ask you to pick a port - I run cockpit on many of my test servers and in fact recommend using it. Can you check if you see a port conflict? What does 'systemctl status cockpit' tell you?

**Comment by bayeslearner** [comment]
I notice the cockpit is accessible through IP and not by hostname anymore from another host on the lan.
